apiVersion: v1
data:
  AwsAccessKeyId: QUtJQVlRUFhEQ082RlJTRVNBTVI=
  AwsSecretAccessKey: RWYxZ0MwUW9LSzEyL04wY3NkOGkyY3IxR3g0K0Q4RW1XN2JFMXp6ZQ==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: cluster-autoscaler
  creationTimestamp: "2023-05-21T15:30:44Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cluster-autoscaler-stest
  uid: cf338604-3664-48c4-8675-b7a04565f386
type: Opaque
